version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    environment:
      RAILS_ENV: production
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
